baseURL = "https://goodfirstissue.dev/"
languageCode = "en-us"
title = "Good First Issue: Make your first open-source contribution"
theme = "lucy"

pluralizelisttitles = false
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsStyle = "monokai"

enableEmoji = true
enableRobotsTXT = false
log = true

disableHugoGeneratorInject = true

cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
include_rss            = true                          # include RSS <link> tag in <head> and show RSS icon
i18n_flags             = true                         # whether to display small country flags for available translations

disableKinds = ["taxonomyTerm"]

[params]
description = "Making your first open-source contribution is easier than you think. Good First Issue is a curated list of issues from popular open-source projects that you can fix easily. Start today!"
keywords = "good first issue, open source, github, beginner, pull requests, help wanted, deepsource"
facebookAppId = "560903037813271"

[blackfriday]
hrefTargetBlank = true